---
name: ci-golang-workflow
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Run test
        working-directory: ./lab-ci/go
        run: go test
      - name: Run program
        working-directory: ./lab-ci/go
        run: go run math.go
