---
name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - developer
jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.14','1.15']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }} #1.15
      - name: Run test
        working-directory: ./lab-ci/go
        run: go test
      - name: Run program
        working-directory: ./lab-ci/go
        run: go run math.go
